# Generated by Django 5.2.2 on 2025-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnus',
            name='location',
        ),
        migrations.RemoveField(
            model_name='alumnus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alumnus',
            name='profession',
        ),
        migrations.AddField(
            model_name='alumnus',
            name='admission_number',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnus',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumnus',
            name='kcse_year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
