# Generated by Django 5.2.2 on 2025-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_remove_alumnus_location_remove_alumnus_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnus',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='image',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='year',
        ),
        migrations.AddField(
            model_name='alumni',
            name='admission_number',
            field=models.CharField(default='ADM0000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='full_name',
            field=models.CharField(default='Unknown Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='kcse_year',
            field=models.PositiveIntegerField(default=2015),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='phone',
            field=models.CharField(default='0700000000', max_length=20),
            preserve_default=False,
        ),
    ]
