# Generated by Django 5.2.2 on 2025-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_delete_alumnus_remove_alumni_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
