# Generated by Django 5.2.2 on 2025-07-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alter_alumni_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='kcse_year',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
