# Generated by Django 5.2.2 on 2025-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_alumni_kcse_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
            preserve_default=False,
        ),
    ]
