# Generated by Django 5.2.2 on 2025-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alumni_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
